builds:
  - env:
    - CGO_ENABLED=1  # go-sqlite3 requires cgo to work
    goos:
    - darwin
    goarch:
    - amd64
    - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
checksum:
  disable: true
