builds:
  - env:
    - CGO_ENABLED=1  # go-sqlite3 requires cgo to work
    goos:
    - linux
    goarch:
    - amd64
    - arm64
    overrides:
    - goos: linux
      goarch: arm64
      env:
      - CC=aarch64-linux-gnu-gcc
    - goos: linux
      goarch: amd64
      env:
      - CC=gcc
    ldflags:
      - -s -w -X main.Version={{.Version}}
checksum:
  disable: true
